version: "3.4"

networks:
  appnetwork:

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi_be
    container_name: webapi_api
    build:
      context: .
      dockerfile: WebApi/Dockerfile.stag
    environment:
      - ASPNETCORE_ENVIRONMENT=stag
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - NODE_ENV=stag
    ports:
      - "5065:80"
      - "7065:443"
    networks:
      - appnetwork
  cronjob:
    image: ${DOCKER_REGISTRY-}webapi_cronjob
    container_name: webapi_cronjob
    build:
      context: .
      dockerfile: WebApi.CronJob/Dockerfile
    networks:
      - appnetwork
    depends_on:
      - webapi
  clients:
    container_name: webapi_fe
    image: ${DOCKER_REGISTRY-}webapi_fe
    build:
      context: .
      dockerfile: WebApi/ClientApp/Dockerfile.stag
    ports:
      - "44421:44421"
    depends_on:
      - webapi
    volumes:
      - ./WebApi/ClientApp:/app
    networks:
      - appnetwork
